entityType: ent
entitySet: "{entityType}-nodes"

bucketType: chunk

strFeature: str
afterFeature: after

features:
  - eid
  - kind

keywordFeatures:
  - kind

defaultValues:
  kind: PER

spaceEscaped: false

transform:
  d: ""
  da: ""
  dal: ""
  de: ""
  del: ""
  dela: ""
  der: ""
  detto: ""
  di: ""
  el: ""
  en: ""
  et: ""
  giovanni: "gio"
  il: ""
  la: ""
  le: ""
  of: ""
  tot: ""
  van: ""
  von: ""
  y: ""
  zu: ""
