@node
@author=Christofforo Suriano
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@contributors2=Nina Lamal
@contributors3=Helmer Helmers
@conversionCode=tt
@conversionMethod=derived
@converter=Dirk Roorda (Text-Fabric)
@dateWritten=2024-09-02T11:44:50Z
@description=Place where the letter was received
@descriptionTf=Critical edition
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@institute3=NL-LAB
@language=it
@schema=TEI + suriano
@sourceFormat=TEI
@teiVersion=not specified
@title=Letters
@valueType=str
@version=0.5.1e
@writtenBy=Text-Fabric
@writtenBy=Text-Fabric
@dateWritten=2024-09-02T11:48:44Z

1773792	Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy


Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
The Hague, South Holland, Netherlands
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy


Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy



Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy


Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy

Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
Venice, Veneto, Italy
