@node
@author=Christofforo Suriano
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@contributors2=Nina Lamal
@contributors3=Helmer Helmers
@conversionCode=tt
@conversionMethod=derived
@converter=Dirk Roorda (Text-Fabric)
@dateWritten=2024-10-08T12:15:14Z
@description=Recipient of the letter
@descriptionTf=Critical edition
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@institute3=NL-LAB
@language=it
@schema=TEI + suriano
@sourceFormat=TEI
@teiVersion=not specified
@title=Letters
@valueType=str
@version=0.7.1e
@writtenBy=Text-Fabric
@writtenBy=Text-Fabric
@dateWritten=2024-10-09T16:20:39Z

1803109	Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
