interfaceDefaults:
  showGraphics: true
provenanceSpec:
  extraData: ner
  graphicsRelative: thumb
typeDisplay:
  pb:
    label: '<span class=editorial>folio {facs}</span>'
    template: '<span class=editorial>folio {n}</span>'
    graphics: true
  metamark:
    label: '{facs}'
    template: '{facs}'
  ptr:
    label: '<span class=editorial>note {n}</span>'
    template: '<span class=editorial>note {n}</span>'
