@node
@author=Christofforo Suriano
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@contributors2=Nina Lamal
@contributors3=Helmer Helmers
@conversionCode=tt
@conversionMethod=derived
@converter=Dirk Roorda (Text-Fabric)
@dateWritten=2024-09-18T22:11:04Z
@description=Recipient of the letter
@descriptionTf=Critical edition
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@institute3=NL-LAB
@language=it
@schema=TEI + suriano
@sourceFormat=TEI
@teiVersion=not specified
@title=Letters
@valueType=str
@version=0.7.0e
@writtenBy=Text-Fabric
@writtenBy=Text-Fabric
@dateWritten=2024-09-18T22:13:17Z

1807239	Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
