@node
@author=Christofforo Suriano
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@contributors2=Nina Lamal
@contributors3=Helmer Helmers
@conversionCode=tt
@conversionMethod=derived
@converter=Dirk Roorda (Text-Fabric)
@description=Recipient of the letter
@descriptionTf=Critical edition
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@institute3=NL-LAB
@language=it
@schema=TEI + suriano
@sourceFormat=TEI
@teiVersion=not specified
@title=Letters
@valueType=str
@version=2.0.0
@writtenBy=Text-Fabric
@dateWritten=2025-11-19T08:09:51+00:00Z

1849525	Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice

























Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
Doge and Senate of Venice
